package com.kssidll.workin.ui.theme

import androidx.compose.ui.graphics.*

val light_primary = Color(0xFFF1F2FC)
val light_onPrimary = Color(0xFF1B1B1F)
val light_secondary = Color(0xFFB8AFC8)
val light_onSecondary = Color(0xFF2D0E34)
val light_error = Color(0xFFB3261E)
val light_onError = Color(0xFFFFFFFF)
val light_errorContainer = Color(0xFFF9DEDC)
val light_onErrorContainer = Color(0xFF410E0B)
val light_outline = Color(0xFF79747E)
val light_background = Color(0xFFFEFBFF)
val light_onBackground = Color(0xFF1B1B1F)
val light_surface = Color(0xFFFEFBFF)
val light_onSurface = Color(0xFF1B1B1F)
val light_scrim = Color(0xFF000000)

val dark_primary = Color(0xFF23242A)
val dark_onPrimary = Color(0xFFE3E2E6)
val dark_secondary = Color(0xFF5D3A62)
val dark_onSecondary = Color(0xFFFED6FF)
val dark_error = Color(0xFFF2B8B5)
val dark_onError = Color(0xFF601410)
val dark_errorContainer = Color(0xFF8C1D18)
val dark_onErrorContainer = Color(0xFFF9DEDC)
val dark_outline = Color(0xFF938F99)
val dark_background = Color(0xFF1B1B1F)
val dark_onBackground = Color(0xFFE3E2E6)
val dark_surface = Color(0xFF1B1B1F)
val dark_onSurface = Color(0xFFE3E2E6)
val dark_scrim = Color(0xFFFFFFFF)
